server:
  port: 9898
spring:
  profiles:
    active: "dev"
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:33060/java-meedu?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false"
    username: "root"
    password: "root"
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5       # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true     # 自动提交
  # Redis配置
  data:
    redis:
      host: "127.0.0.1"
      port: 6379
      password:
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-wait: 30000 # 连接池最大阻塞等待时间(使用负数表示没有限制,默认-1)
          max-active: 100 # 连接池最大连接数(使用负数表示没有限制,默认8)
          max-idle: 20    # 连接池中的最大空闲连接(默认8)
          min-idle: 5     # 连接池中的最小空闲连接(默认0)
  # 线程池配置
  task:
    execution:
      pool:
        max-size: 8 #最大线程数量
        core-size: 4 #初始化线程数量
        queue-capacity: 1000 #队列最大长度
        keep-alive: 60s #线程终止前允许保存的最大时间
      shutdown:
        await-termination: true
      thread-name-prefix: "playedu-default-thread"

# Minio
minio:
  access-key: "username"
  secret-key: "password"
  end-point: "http://127.0.0.1:9000"
  bucket: "playedu"
  domain: "https://dev-local3.meedu.vip/"

mybatis:
  mapper-locations: classpath:mapper/*.xml

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PlayEdu
playedu:
  # 图形验证码
  captcha:
    expire: 300 #有效期[单位:秒,默认5分钟]
    cache-prefix: "captcha:key:" #存储key的前缀
  # JWT
  jwt:
    key: "eJTJSLPv13fw9twbuPoeicypLqnSfYWL" #32个字符,加密key用来加密jwt的数据[运行本系统之前请务必修改]
    expire: 1296000 #token有效期[单位:秒,默认15天]
    cache-black-prefix: "jwt:blk:" #主动注销的token黑名单缓存前缀

