server:
  port: 9898
spring:
  profiles:
    active: "dev"
  aop:
    auto: true
    proxy-target-class: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 5MB
      max-file-size: 5MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/dbname?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false"
    username: ""
    password: ""
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5       # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true     # 自动提交
  # Redis配置
  data:
    redis:
      host: "127.0.0.1"
      port: 6379
      password:
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-wait: 30000 # 连接池最大阻塞等待时间(使用负数表示没有限制,默认-1)
          max-active: 100 # 连接池最大连接数(使用负数表示没有限制,默认8)
          max-idle: 20    # 连接池中的最大空闲连接(默认8)
          min-idle: 5     # 连接池中的最小空闲连接(默认0)
  # 线程池配置
  task:
    execution:
      pool:
        max-size: 4 #最大线程数量
        core-size: 2 #初始化线程数量
        queue-capacity: 10000 #队列最大长度
        keep-alive: 60s #线程终止前允许保存的最大时间
      shutdown:
        await-termination: true
      thread-name-prefix: "playedu-default-thread"

mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  global-config:
    banner: false
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sa-token:
  token-name: "Authorization"
  timeout: 1296000 #token有效期[单位:秒,默认15天]
  is-concurrent: false #限制同时登录
  is-share: false
  jwt-secret-key: "playeduxyz"
  token-prefix: "Bearer"

playedu:
  limiter:
    duration: 60
    limit: 240
